### ISSUE TITLE
Updated cabal-install-1.20

### ISSUE THREAD

**Issue by snoyberg** [hvr/multi-ghc-travis#14]
There's a nasty bug regarding test output streaming in the currently provided cabal-install-1.20. Would it be possible to release a new version based on the latest Cabal and cabal-install in that major version number?

**Comment by hvr** [comment]
This most likely won't be fixed due to lack of time (focus is currently on nix-style cabal). And I suspect that there's little demand for updating cabal-install-1.20 at this point. Consequently I'll tentatively close this one as wont-fix.
