### ISSUE TITLE
alex-3.1.4 and happy-1.19.5

### ISSUE THREAD

**Issue by snakamura** [hvr/multi-ghc-travis#16]
Do you have a plan to add alex-3.1.4 and happy-1.19.5 to your ppa?

I'm trying to build my package that uses language-javascript on travis using ghc-7.10.1 and it fails to build because alex-3.1.3 doesn't have Applicative instance for Alex. I'd appreciate it if you added these libraries to your ppa.

**Comment by hvr** [comment]
They have been built on launchpad, and should become available via `apt-get install` in the next couple of minutes; I'm closing this issue optimistically, please re-open if something goes wrong

**Comment by snakamura** [comment]
They worked. Thank you!
