### ISSUE TITLE
"WARNING: The following packages cannot be authenticated!"

### ISSUE THREAD

**Issue by snoyberg** [hvr/multi-ghc-travis#22]
I just saw the following error in one of my builds:

```
WARNING: The following packages cannot be authenticated!
  cabal-install-1.20 ghc-7.8.4
E: There are problems and -y was used without --force-yes
```

Travis link: https://travis-ci.org/fpco/stackage-server/builds/62647096

Any idea what would have triggered this?

**Comment by snoyberg** [comment]
Not sure if you changed anything, but my builds starting working again (e.g., https://travis-ci.org/fpco/stackage-server/builds/62648427). Feel free to close, only not doing so myself in case there's some value to you in this report.

**Comment by hvr** [comment]
Sounds like a glitch letting `apt-get` lose the gpg-meta-info
