### ISSUE TITLE
Investigate ways to better manage updating the travis file

### ISSUE THREAD

**Issue by nomeata** [hvr/multi-ghc-travis#25]
I use this travis file on several projects, but I am having a hard time to keep it up-to-date with recent improvements. It would be nice if there was a way where I only add the relevant configuration (what GHC versions to test, and for which combinations failure is non-critical) and have the rest pulled somehow automatically.

Unfortunately, I do not have an idea on how this could be accomplished. How does travis react to a self-modifying .travis file? :-)

Also, have you tried to contact the travis guys and checked if they want to officially support this configuration?

**Comment by hvr** [comment]
According to

http://docs.travis-ci.com/user/ci-environment/#Haskell-VM-images

Travis currently support multiple GHCs, but not all the versions my PPA supports. See also discussion in travis-ci/travis-ci#882

I *think* Travis-CI uses this recipes over at https://github.com/travis-ci/travis-cookbooks/tree/master/ci_environment/haskell for their Haskell VMs

**Comment by FranklinChen** [comment]
I've run into this maintenance problem also, with multiple copies of .travis.yml running around. Here's an idea:

Create an actual model (data type) of what a multi-ghc Travis configuration means (rather than random stringly-typed YAML with manual commenting out here and there), create an API for generating and updating a .travis.yml according to some options, publish all this as a package. And this library should have Travis building itself.

**Comment by hvr** [comment]
Btw, there's now [`make_travis_yml.hs`](https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml.hs) as a first modest step...

**Comment by FranklinChen** [comment]
Cool, I'll try it out.

**Comment by FranklinChen** [comment]
I wish Travis documented better what was supported where. I tried this script but the result was a failure to find GHC 7.10.2, so I'm going to have to revert to the old way.

**Comment by hvr** [comment]
@FranklinChen Sadly GHC 7.10.2 is still stuck in Travis' whitelist review queue, see https://github.com/travis-ci/travis-ci/issues/4478 and https://github.com/travis-ci/apt-package-whitelist/pull/686

**Comment by phadej** [comment]
I hope this is healthy competition, https://github.com/phadej/travis-meta-yaml. And I like @hvr idea of (ab)using `tested-with` to generate matrix. I'll borrow that idea.

**Comment by FranklinChen** [comment]
I noticed that the generated `.travis.yml` unfortunately does not install `happy` or `alex`.

**Comment by phadej** [comment]
I think that v2 script, especially with `--regenerate` flag is good.
