### ISSUE TITLE
cabal: The program 'ghc' version >=6.4 is required but it could not be found.

### ISSUE THREAD

**Issue by mokus0** [hvr/multi-ghc-travis#29]
I'm not sure why but it appears GHC 7.10.2 is not being installed (the "ghc --version" check fails too with "ghc: command not found").  This is from a travis config build by make_travis_yml.hs with "tested-with: GHC == 7.*", and all other versions succeeded.

The build log on travis: https://travis-ci.org/mokus0/dependent-sum/builds/76683955

The full 7.10.2 job log:

    Using worker: worker-linux-docker-ddd8bb34.prod.travis-ci.org:travis-linux-7
    system_info
    Build system information
    Build language: c
    Build image provisioning date and time
    Thu Feb  5 15:09:33 UTC 2015
    Operating System Details
    Distributor ID: Ubuntu
    Description:    Ubuntu 12.04.5 LTS
    Release:    12.04
    Codename:   precise
    Linux Version
    3.13.0-29-generic
    Cookbooks Version
    a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
    GCC version
    gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
    Copyright (C) 2011 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    LLVM version
    clang version 3.4 (tags/RELEASE_34/final)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    Pre-installed Ruby versions
    ruby-1.9.3-p551
    Pre-installed Node.js versions
    v0.10.36
    Pre-installed Go versions
    1.4.1
    Redis version
    redis-server 2.8.19
    riak version
    2.0.2
    MongoDB version
    MongoDB 2.4.12
    CouchDB version
    couchdb 1.6.1
    Neo4j version
    1.9.4
    RabbitMQ Version
    3.4.3
    ElasticSearch version
    1.4.0
    Installed Sphinx versions
    2.0.10
    2.1.9
    2.2.6
    Default Sphinx version
    2.2.6
    Installed Firefox version
    firefox 31.0esr
    PhantomJS version
    1.9.8
    ant -version
    Apache Ant(TM) version 1.8.2 compiled on December 3 2011
    mvn -version
    Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
    Maven home: /usr/local/maven
    Java version: 1.7.0_76, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/java-7-oracle/jre
    Default locale: en_US, platform encoding: ANSI_X3.4-1968
    OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
    git.checkout
    0.09s$ git clone --depth=50 --branch=master git://github.com/mokus0/dependent-sum.git mokus0/dependent-sum
    Cloning into 'mokus0/dependent-sum'...
    remote: Counting objects: 315, done.
    remote: Compressing objects: 100% (21/21), done.
    remote: Total 315 (delta 10), reused 0 (delta 0), pack-reused 293
    Receiving objects: 100% (315/315), 48.08 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (118/118), done.
    Checking connectivity... done.
    $ cd mokus0/dependent-sum
    $ git checkout -qf 2ecc274d93cfd2315df52ff8a223a07790dcfdbe
    apt
    Adding APT Sources (BETA)
    $ export DEBIAN_FRONTEND=noninteractive
    1.46s$ sudo -E apt-add-repository -y "ppa:hvr/ghc"
    gpg: keyring `/tmp/tmpPfiieO/secring.gpg' created
    gpg: keyring `/tmp/tmpPfiieO/pubring.gpg' created
    gpg: requesting key F6F88286 from hkp server keyserver.ubuntu.com
    gpg: /tmp/tmpPfiieO/trustdb.gpg: trustdb created
    gpg: key F6F88286: public key "Launchpad PPA for Herbert V. Riedel" imported
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)
    OK
    Installing APT Packages (BETA)
    Disallowing packages: ghc-7.10.2
    If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
    $ export DEBIAN_FRONTEND=noninteractive
    4.71s$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
    7.20s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install cabal-install-1.22
    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following NEW packages will be installed:
      cabal-install-1.22
    0 upgraded, 1 newly installed, 0 to remove and 205 not upgraded.
    Need to get 2,951 kB of archives.
    After this operation, 12.7 MB of additional disk space will be used.
    Get:1 http://ppa.launchpad.net/hvr/ghc/ubuntu/ precise/main cabal-install-1.22 amd64 1.22.6.0-1~precise [2,951 kB]
    Fetched 2,951 kB in 1s (2,794 kB/s)
    Selecting previously unselected package cabal-install-1.22.
    (Reading database ... 71420 files and directories currently installed.)
    Unpacking cabal-install-1.22 (from .../cabal-install-1.22_1.22.6.0-1~precise_amd64.deb) ...
    Setting up cabal-install-1.22 (1.22.6.0-1~precise) ...
    This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
    If you require sudo, add 'sudo: required' to your .travis.yml
    See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
    Setting environment variables from .travis.yml
    $ export CABALVER=1.22
    $ export GHCVER=7.10.2
    $ export CC=: #GHC 7.10.2
    cache.1
    Setting up build cache
    $ export CASHER_DIR=$HOME/.casher
    0.05s$ Installing caching utilities
    0.37sattempting to download cache archive
    fetching master/cache--compiler-GHC7.10.2.tgz
    fetching master/cache--compiler-GHC7.10.2.tbz
    could not download cache
    0.28sadding /home/travis/.cabsnap to cache
    adding /home/travis/.cabal/packages to cache
    $ : #GHC 7.10.2 --version
    before_install.1
    0.00s$ unset CC
    before_install.2
    0.00s$ export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
    install.1
    0.02s$ cabal --version
    cabal-install version 1.22.6.0
    using version 1.22.4.0 of the Cabal library 
    install.2
    0.01s$ echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
    /home/travis/build.sh: line 41: ghc: command not found
     [?]
    install.3
    0.00s$ if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ]; then zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz > $HOME/.cabal/packages/hackage.haskell.org/00-index.tar; fi
    install.4
    4.37s$ travis_retry cabal update -v
    Config file path source is default config file.
    Config file /home/travis/.cabal/config not found.
    Writing default configuration to /home/travis/.cabal/config
    Downloading the latest package list from hackage.haskell.org
    Downloaded to /home/travis/.cabal/packages/hackage.haskell.org/00-index.tar.gz
    Updating the index cache file...
    install.5
    0.00s$ sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
    0.01s$ cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
    cabal: The program 'ghc' version >=6.4 is required but it could not be found.
    The command "cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt" failed and exited with 1 during .
    Your build has been stopped.

**Comment by hvr** [comment]
Sadly, this is a [known issue](https://github.com/hvr/multi-ghc-travis/blob/master/README.md#known-issues), see also

 - https://github.com/travis-ci/travis-ci/issues/4478 and
 - https://github.com/travis-ci/apt-package-whitelist/pull/686

**Comment by mokus0** [comment]
Ah, sorry I missed that.  It's not a big deal, I'm just updating my tests and thought since 7.10.2 was out I'd add it.  For what it's worth, I did read through all the issues before posting this one :)

**Comment by hvr** [comment]
GHC 7.10.2 has been finally whitelisted!
