### ISSUE TITLE
Debian packages — Dead link in PPA description

### ISSUE THREAD

**Issue by Blaisorblade** [hvr/multi-ghc-travis#31]
- The description of https://launchpad.net/~hvr/+archive/ubuntu/ghc links to http://deb.haskell.org/, which is dead.
- I've in fact been looking for GHC Debian packages to use with Jenkins's Debian image. I currently hack things to use your trusty packages on jessie, which seems to work AFAICS (very light testing). (Official packages are unsuitable as expected, I've checked https://packages.debian.org/sid/amd64/ghc/filelist).

Here's my `Dockerfile`, with the command installing your packages on Jenkins (note the hack, done via the `sed` call).
```
FROM jenkins

USER root

RUN apt-get update && apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:hvr/ghc && \
    sed -i 's/jessie/trusty/' /etc/apt/sources.list.d/hvr-ghc-jessie.list && \
    apt-get -y remove --purge software-properties-common && \
    apt-get update && \
    apt-get -y install ghc-7.10.1 cabal-install-1.22 cabal-install-1.18 ghc-7.8.4 openjdk-7-jdk && \
    apt-get -y autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins

ENV JENKINS_OPTS --httpPort=8080

EXPOSE 8080
```

**Comment by hvr** [comment]
@Blaisorblade  I just realised I forget to close this issue when this has was resolved: There's http://downloads.haskell.org/debian/ now!
