### ISSUE TITLE
The version of Cabal being used has changed (was Cabal-1.22.2.0, now Cabal-1.22.4.0).

### ISSUE THREAD

**Issue by nomeata** [hvr/multi-ghc-travis#35]
Not sure if this is a bug in Cabal, or an issue with the packages in your repository. I get failures like this one https://travis-ci.org/nomeata/ghc-heap-view/jobs/85001287 because the ghc-7.10 package in your repo ships `Cabal-1.22.2.0`, while your `cabal-1.22` package is built against `1.22.4.0`:
```
$ cabal test

cabal: You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.22.2.0, now Cabal-1.22.4.0).
```

**Comment by phadej** [comment]
That's looks like a bug in `Cabal`. You have `Custom` as a build-type, so `cabal-install` should use `Setup.hs` always AFAIK. In other words the `Cabal` library `cabal-install` is compiled against shouldn't ever be "used".

**Comment by phadej** [comment]
@nomeata could you try with `ghc-7.10.1` and `ghc-7.10.2` but `cabal-head`?

**Comment by nomeata** [comment]
Ok, so the bug might be that while `cabal build` uses `Setup.hs`, `cabal test` does not.

**Comment by nomeata** [comment]
Also occurs with Cabal head and 7.10.2.

How up-to-date is Cabal-head? There is https://github.com/haskell/cabal/issues/1938 which looks related, but claims to fixed since June.

**Comment by nomeata** [comment]
Anyways, most likely not a bug here, but rather in Cabal.

**Comment by markhibberd** [comment]
Pgyoaajokkqadafqgqf

**Comment by nomeata** [comment]
Am 17. Oktober 2015 02:37:27 MESZ, schrieb markhibberd <notifications@github.com>:
>Pgyoaajokkqadafqgqf

I wholeheartedly agree.


>https://github.com/hvr/multi-ghc-travis/issues/35#issuecomment-148871215
