### ISSUE TITLE
Builds should run in the environment generated by "sdist"

### ISSUE THREAD

**Issue by peti** [hvr/multi-ghc-travis#49]
The singularly most common reason for test suite failures in NixOS is that people run the test suite on Travis in a git checkout of their repository, which contains all files, naturally. Since it's easy to forget to add required test modules or data files to the Cabl file, however, these will then be missing in the generated release tarball that people upload to Hackage, and then their project doesn't compile. Thus, it would be great, if your setup could run all builds and tests in a source directory that comes from extracting an sdist-generated tarball rather than running them in the git checkout.

**Comment by hvr** [comment]
fwiw, the script-generators do that: https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs#L154-L163

**Comment by phadej** [comment]
@hvr would it make sense to modify `make_travis_yml.hs` script? I'm still using it (don't know why though), when generating `.travis.yml` for other people packages?

**Comment by hvr** [comment]
@phadej there's something similiar in there as well:

https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml.hs#L165-L169

anyway, I'm planning to embrace "build-out-of-sdist" a bit more in the `_2.hs`-script; cause the current one doesn't catch missing data-files.

**Comment by peti** [comment]
That new `make_travis_yml_2.hs` script works really well!

**Comment by hvr** [comment]
@peti fyi, I've manually prototyped at https://github.com/haskell/hackage-server/blob/master/.travis.yml how to build everything within a `sdist`-environment. I'll soon enhance the v2 script to allow you to generate such a script
