### ISSUE TITLE
make_travis_yml_2.hs doesn't detect compiler error

### ISSUE THREAD

**Issue by peti** [hvr/multi-ghc-travis#52]
Check out https://travis-ci.org/peti/pico-prolog/jobs/135561591:

~~~
Data/Vector/Fusion/Stream/Size.hs:25:10:
    Warning: No explicit method nor default method for `signum'
    In the instance declaration for `Num Size'
[ 4 of 19] Compiling Data.Vector.Internal.Check ( Data/Vector/Internal/Check.hs, dist/build/Data/Vector/Internal/Check.o )
[ 5 of 19] Compiling Data.Vector.Fusion.Stream.Monadic ( Data/Vector/Fusion/Stream/Monadic.hs, dist/build/Data/Vector/Fusion/Stream/Monadic.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package transformers-0.3.0.0 ... <command line>: can't load .so/.DLL for: HStransformers-0.3.0.0-330efd28cf24d8cb9a5fe8fa655d885d5db855228308e159f3d7459f5576a972 (libHStransformers-0.3.0.0-330efd28cf24d8cb9a5fe8fa655d885d5db855228308e159f3d7459f5576a972.so: cannot open shared object file: No such file or directory)

travis_time:end:158a883c:start=1465218060448809022,finish=1465218089177765635,duration=28728956613
[0K
[32;1mThe command "cabal new-build ${TEST} ${BENCH}" exited with 0.[0m
~~~~

The build fails with a nasty compiler/linker error, but Travis-CI won't detect that; the build is marked as successful in the end.

**Comment by peti** [comment]
Another, similar error happened in https://travis-ci.org/peti/hledger-interest/jobs/135560940:

~~~~
Preprocessing library hledger-lib-0.27.1...

Hledger/Data/Types.hs:23:8:
    Could not find module `GHC.Generics'
    It is a member of the hidden package `ghc-prim'.
    Perhaps you need to add `ghc-prim' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

travis_time:end:13841d3c:start=1465213162062566762,finish=1465213163946251238,duration=1883684476
[0K
[32;1mThe command "cabal new-build --disable-tests --disable-benchmarks" exited with 0.[0m
~~~~

The build is also marked as successful despite the obvious error.

**Comment by hvr** [comment]
@peti unfortunately this is a Bug in `cabal`, so we'll have to wait until there's an upstream fix

**Comment by hvr** [comment]
Fyi, the 1.24 branch of cabal has a fix for that silent exit-0 failures, and I just rebuilt the cabal-1.24 package in my ppa with the latest 1.24 branch tip for Travis' benefit

so this should work now... if not, please reopen

**Comment by peti** [comment]
I've switched several of my more involved projects to the new build script now and it works like a charm. Thank you very much for the effort you've put into this tool; it's very useful to me and many others and I believe it has a great impact towards making Haskell packages more reliable and thus easier to build, distribute, and re-use.
