### ISSUE TITLE
v2 script cannot run doctest test suites

### ISSUE THREAD

**Issue by peti** [hvr/multi-ghc-travis#54]
`doctest` performs some kind of magic to evaluate source code found in comments. Therefore, doctest suites need to be run in an environment that has access to the compiler and libraries that were used to build the package. The v2 generator, however, executes the test suite outside of that environment, which means the test suite will fail: https://travis-ci.org/peti/hsemail/jobs/145211013.

**Comment by phadej** [comment]
- for GHC-8+ there are `.ghc.environment` files which helps (you have to find the files yourself).
- for older ghc you could use `cabal-doctest`

**Comment by phadej** [comment]
I'll close this ticket for now. The proper `new-doctest` solution is tracked in https://github.com/haskell/cabal/issues/4500
