### ISSUE TITLE
[Q] Is it safe to cache ~/.cabal ~/.ghc?

### ISSUE THREAD

**Issue by steshaw** [hvr/multi-ghc-travis#57]
Given [Michael Snoyman's article on Travis configuration](https://www.fpcomplete.com/blog/2016/02/updated-haskell-travis-config) for Stack and Cabal, I'm wondering if it's safe to do

```
cache:
  directories:
  - ~/.ghc
  - ~/.cabal
  - ~/.stack
```

without any thought to the .cabsnap or installation plan?

**Comment by phadej** [comment]
As far as scripts in this repository are concerned, caching `~/.ghc` would break the builds. The dependencies and the package under test is installed there, so in some next run you'll definitely run into one occurence of Cabal Hell.

- `~/.cabal/packages` are cached already though
- `~/.stack` is safe to cache

**Comment by hvr** [comment]
Like @phadej said. However, the new `cabal new-build` feature uses `~/.cabal/store` in place of `~/.ghc`, and that one's safe to cache. But be careful when caching other parts of `~/.cabal` as you'll easily end up with huge caches (in the order of ~1GiB), which I'm worrying that Travis admins may start noticing if this gets overboard...

**Comment by steshaw** [comment]
Hmmm, the travis config over at [updated-travis-config](https://www.fpcomplete.com/blog/2016/02/updated-haskell-travis-config) looks very similar to those here (they are based on those here). I peeked at a few well-known Haskell projects that seemed to be using the recommended scheme AFAICT…

I'd like to understood more, if I can press you further. Idris is still being tested with a [v1](https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml.hs)-style script because we have to test the versions that folks will have by default in certain Linux distributions. We don't use Stack (on Travis at least). Could you explain why it's unsafe to cache `~./ghc` and `~/.cabal` (or throw some references at me!). I'd also like to understand why the "installplan.txt" diff is doing.

It would be great to cache binary builds of dependencies and even the "package under test" if possible.

**Comment by phadej** [comment]
`installplan.txt` is essentially a list of dependencies and their versions, so if something new comes we know when we should wipe a cache. We don't store installed packages directly in `~/.ghc` as the global database would interfere with solving the install plan.

What we do here is poor man `cabal sandboxes`, and we use the sandbox only when stuff there is the one we'd install starting with clean table.

`~/.cabal/packages/hackage.haskell.org` for example stores the tarballs for downloaded packages, so it's likely to grow over time.

**Comment by steshaw** [comment]
Okay, thanks.
