### ISSUE TITLE
libHShaskeline-0.7.1.2-ghc7.8.3.so: cannot open

### ISSUE THREAD

**Issue by Mikolaj** [hvr/multi-ghc-travis#60]
In line 223 of https://travis-ci.org/LambdaHack/LambdaHack/jobs/166484038

**Comment by Mikolaj** [comment]
It works now. Might have been a net fluke. Cheers!

**Comment by hvr** [comment]
@Mikolaj it was a glitch in the packaging C:-)   (DSOs moved accidentally into the `ghc-dyn` packages while I tweaked the packaging to support Ubuntu Yakkety; I fixed it as soon as I noticed it)
