### ISSUE TITLE
Installing cabal-install-1.24 without installing GHC fails during apt-install

### ISSUE THREAD

**Issue by tmcdonell** [hvr/multi-ghc-travis#62]
This seems to be a recent change, because I have been doing it for a while (I grab GHC via stack, so that I can upgrade the Cabal library). Here is an example of the error:

https://travis-ci.org/tmcdonell/travis-test/builds/173776504#L403

Looks like it is attempting to add a symlink to `/opt/ghc/bin`, which doesn't exist because that belongs to one of the `ghc` packages.

The following build, which also includes `ghc-8.0.1`, succeeds:

https://github.com/tmcdonell/travis-test/compare/6d5cef2f07b0...324efb0b2734
https://travis-ci.org/tmcdonell/travis-test/builds/173777078

This build which uses `cabal-install-1.22` and no `ghc` also succeeds:

https://github.com/tmcdonell/travis-test/compare/324efb0b2734...635f96d0165f
https://travis-ci.org/tmcdonell/travis-test/builds/173779024

Here is a build from 4 days ago with `cabal-install-1.24` and no ghc, which again succeeds:

https://travis-ci.org/tmcdonell/accelerate-llvm/jobs/172836280/config

**Comment by hvr** [comment]
Thanks for the report! I'll try to fix this asap

**Comment by hvr** [comment]
@tmcdonell if you try again in about ~30 minutes, the new `cabal-install-1.24` package should include an empty `/opt/ghc/bin` folder

**Comment by tmcdonell** [comment]
Seems to be working again, thanks for the speedy fix! (:
