### ISSUE TITLE
Travis seems to support setting cache name

### ISSUE THREAD

**Issue by phadej** [hvr/multi-ghc-travis#63]
https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

> If these characteristics are shared by more than one job in a build matrix, they will share the same URL on the network. This could corrupt the cache, or the cache may contain files that are not usable in all jobs using it. In this case, we advise you to add a defining public environment variable name; e.g.,

```
CACHE_NAME=JOB1
```

> to `.travis.yml`.

**Comment by hvr** [comment]
interesting/good-to-know; but at this point I don't think the current v2 travis script generator needs this

**Comment by phadej** [comment]
the different jobs are differentiated based on `compiler` already?

**Comment by hvr** [comment]
yes... that's at least I observed when I looked at the generated cache-ids

**Comment by hvr** [comment]
> Note that this makes our cache not network-local, it’s still bound to network bandwidth and DNS resolutions for S3. That impacts what you can and should store in the cache. If you store archives larger than a few hundred megabytes in the cache, it’s unlikely that you’ll see a big speed improvement.

This actually reminds me to implement GC; at least we don't include full GHC installations in the travis cache... ;-)

**Comment by phadej** [comment]
If v2 script would support building with different lts-snapshots / package-sets (in different jobs), than this might be needed, as compiler alone won't be enough to differentiate caches.

OTOH it will take less time to test different package-sets inside single job.

I close this issue, it was meant as FYI, and that is accomplished.

**Comment by hvr** [comment]
yeah, especially since travis limits the maximum parallelism to about 5 jobs, I saw little benefit in spreading LTS snapshots across multiple jobs
