### ISSUE TITLE
Depending on paths module from test-suite in make_travis_yml_2

### ISSUE THREAD

**Issue by bergmark** [hvr/multi-ghc-travis#75]
`feed` has some declared data-files and the test suite has declared `Paths_feed` as an other-module

Using `make_travis_yml_2` I get the following failure about not finding those files (https://travis-ci.org/bergmark/feed/jobs/214952725):

```
ERROR: /home/travis/.cabal/share/x86_64-linux-ghc-7.4.2/feed-0.3.12.0/tests/files/atom.xml: openBinaryFile: does not exist (No such file or directory)
```
 

```
data-files:
  tests/files/rss20.xml
  tests/files/atom.xml
```

usage: `getDataFileName "tests/files/atom.xml"`

I wouldn't have thought of depending on Paths from the test-suite myself... is this an omission in multi-ghc-travis or expected behavior?

**Comment by bergmark** [comment]
Same result for all GHC's by the way.

**Comment by bergmark** [comment]
Workaround: Switch to multi-ghc-travis v1

**Comment by phadej** [comment]
I suspect it's the consequence of per component build/generated files in menest cabal. In other words: you have to declare `Paths` in other modules in all components using them

**Comment by hvr** [comment]
@bergmark you've just hit a limitation of the `new-test` emulation that I'm going to fix with the next commit... :-)

**Comment by hvr** [comment]
@bergmark can you retry w/ the new script?

**Comment by bergmark** [comment]
It works, thanks a bunch!
