### ISSUE TITLE
Have `make_travis_yml_2.hs` test that Haddocks build

### ISSUE THREAD

**Issue by seagreen** [hvr/multi-ghc-travis#76]
"Check for 100% Haddock coverage" is currently listed in the Additional Checks section, but a smaller check that everyone would probably want would be just making sure the Haddocks build.

**Comment by hvr** [comment]
That's a good idea; I'm just waiting for `cabal new-haddock` to become a bit more reliable. But you could experiment yourself by trying to insert an invocation of `cabal new-haddock` in the generated `.travis.yml` scripts and report back how well it works for you.

**Comment by seagreen** [comment]
I tested out `cabal new-haddock` and it works great. I've got it added on hjsonschema's `master` now so if any problems do come up I'll let you know.

**Comment by hvr** [comment]
note to myself: need to workaround https://github.com/haskell/cabal/issues/4506

**Comment by phadej** [comment]
`new--haddock` is in the v2 script
