### ISSUE TITLE
New-style build fails during "sdist"

### ISSUE THREAD

**Issue by peti** [hvr/multi-ghc-travis#81]
I have a strange build failure at https://travis-ci.org/peti/hsyslog/jobs/234171806:

~~~
$ cabal sdist
ghc: can't find a package database at /home/travis/build/peti/hsyslog/dist-newstyle/packagedb/ghc-8.0.2
~~~

That .travis.yml file was generated with the current version (3e1b3847583020f0e83c97fcf4bcfb7c90b78259) of make_travis_yml_2.hs and that error makes no sense to me. When I run `cabal dist` locally, it works just fine. Any idea what  I could do to fix this issue?

**Comment by phadej** [comment]
@peti you should remove `.ghc.environment.*` file (e.g .in `rm -rf dist` line). I run into this today as well.

Could you submit a PR?

**Comment by peti** [comment]
Thank you for the suggestion! The changed removed the error. Unfortunately, now a new error just popped up (https://travis-ci.org/peti/hsyslog/jobs/235778854) which I believe to be unrelated to the travis-ci build instructions, though.

**Comment by phadej** [comment]
@peti, are you sure you use: https://github.com/phadej/cabal-doctest/blob/master/example/Setup.hs like `Setup.hs`, we tweaked it recently to workaround `sdist` issues.

**Comment by peti** [comment]
Man, this has been a long journey. :-/ Now the tests succeed with GHC 8.x, but none of the other compilers can build by project, apparently because the latest `cabal-install` does not provide a copy of the latest `Cabal`? The error during `sdist` looks a bit strange: https://travis-ci.org/peti/hsyslog/jobs/235822039.

**Comment by phadej** [comment]
@peti you don't need to put `cabal-version:  >= 1.24`, the `cabal-version:  >= 1.10` should be enough.

The situation is a bit tricky:
- `custom-setup` section is supported with `Cabal >= 1.24`
- but you only need a `cabal-install` compiled against recent enough `Cabal`
- `Cabal` bundled with GHC can however be anything what `setup-depends` says.
- i.e. different `Cabal`s are used in different stages.

**Comment by peti** [comment]
OK, I see. I took the `>= 1.24` requirement from the `doctest-cabal` example at https://github.com/phadej/cabal-doctest/blob/master/example/example.cabal#L13 and assumed that would be important. Now, after removing it, the situation has improve significantly. There remains only one error with GHC 7.10.x that I cannot explain:

  https://travis-ci.org/peti/hsyslog/jobs/235963325

Any idea how `bytestring` might end up missing? I would think that's a core package of GHC 7.10.x.

**Comment by hvr** [comment]
@peti I'm not sure yet (still looking), this seems to occur only with Cabal-1.22, but setting `setup-depends: Cabal >= 1.24` makes it work.

**Comment by peti** [comment]
Okay, thank you very much for looking at the issue. I've moved the `build-depends` into the conditional, as suggested. This fixes the error we've seen before, but now the build fails with

    setup: The program 'hsc2hs' is required but it could not be found

instead. When I add the `Cabal >= 1.24` constraint, then all builds succeed fine, but without it GHC 7.10.x appears to be in trouble.

**Comment by hvr** [comment]
Your package most likely lacks a  `build-tools: hsc2hs >= x.y && < z` line; future cabal versions will warn about it

**Comment by peti** [comment]
Phew, https://travis-ci.org/peti/hsyslog/builds/237107742 now succeeds on all platforms. Thank you very much for taking the time to walk me through this process, gentlemen.
