### ISSUE TITLE
Add hyperlink-source docs

### ISSUE THREAD

**Issue by snoyberg** [hvr/multi-ghc-travis#9]
I generally use the Ubuntu PPAs for all of my systems (an incredibly useful resource btw), including systems which do Stackage builds. One downside right now is that the docs provided by the PPAs do not include hyperlinked sources, which means that snapshots on stackage.org do not have hyperlinked sources either. It would be convenient to have those included.

Technically, the most recent snapshot includes the sources because I installed GHC 7.8.4 from the tarball and not the PPA, since I didn't think it was available at the time. Now I see that you got the PPA out the door even faster than I anticipated... color me impressed.

**Comment by hvr** [comment]
is this about the docs for the ghc's bundled packages, or rather for packages built by GHC? If it's the latter, is this just a matter of getting `HsColour` installed in some way?

**Comment by snoyberg** [comment]
No, it's the former, the GHC bundled packages.

**Comment by hvr** [comment]
`ghc-$VER-htmldocs` packages starting with "revision" 10 (e.g. `ghc-7.10.2-htmldocs 7.10.2-`**10**`~utopic`) will have this

**Comment by snoyberg** [comment]
I can confirm that 7.10.2-htmldocs-10 works correctly, thank you!

**Comment by hvr** [comment]
(just for the record, all versions back to GHC 7.4.1 should have hyperlinked sources; GHC 7.0/7.2 need more work)

**Comment by snoyberg** [comment]
Awesome, thanks @hvr!
