### ISSUE TITLE
version 2 script does not run hspec-discover

### ISSUE THREAD

**Issue by alanz** [hvr/multi-ghc-travis#90]
The `cabal sdist` command issues a warning that preprocessors have not run

See https://travis-ci.org/alanz/HaRe/jobs/256413803#L856

This results in the generated not being found when the tests run

**Comment by hvr** [comment]
@alanz I just tried it locally, and the problem appears to be two things:

 * the `Spec` module doesn't occur in the test-suites `other-modules`, and so the source-dist is in fact incomplete  (this is what the version 2 script was designed to detect). Note that the released http://hackage.haskell.org/package/HaRe-0.8.4.1/HaRe-0.8.4.1.tar.gz tarball also is incomplete as well

 * You need to specify a tool-dependency on `hspec-discover`, just add something like

    ```
    build-tool-depends: hspec-discover:hspec-discover ^>= 2.4.4
    ```

   to the test-suite stanza. Cabal < 2 will ignore it (but warn about an unknown directive), while Cabal >= 2 will honor it.

**Comment by alanz** [comment]
Thanks. To be honest, I have not been working with new-build on this project, and forgot that the version 2 used that.

But I will make the changes you recommend and see how it goes.

**Comment by alanz** [comment]
So the cabal file is deficient, no problem with this script.
