### ISSUE TITLE
bash syntax error in generated script

### ISSUE THREAD

**Issue by lspitzner** [hvr/multi-ghc-travis#93]
the script contains "zcat blah > *newline* blah" and after moving that part of the script into a case-statement, travis barked about this newline. I haven't tested if the unmodified script works, but perhaps this can be fixed regardless?

**Comment by lspitzner** [comment]
(also, just out of curiosity: any idea where the mystery line number that travis outputs comes from? it does not match in any conceivable way with the real location of this error..)

**Comment by hvr** [comment]
I suspect you're running into some YAML idiosyncracy. One way to debug this is to convert the .travis.yml file to its JSON representation, and see if the shell script fragments get turned into sensible JSON string values.

**Comment by lspitzner** [comment]
right, this was indeed the issue. there is nothing wrong with the original generated script, and i don't even think it can be improved. One just has to be rather careful when putting moving a "plain multiline literal" into a "non-plain literal".

thanks!

**Comment by hvr** [comment]
...and people wonder why I'm not so excited about YAML-all-the-things :-))
